# Generated by Django 4.2.11 on 2024-03-28 06:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0004_alter_message_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sending',
            new_name='Mailing',
        ),
        migrations.RenameModel(
            old_name='Message',
            new_name='MailingMessage',
        ),
    ]
