# Generated by Django 4.2.11 on 2024-03-29 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_sending_mailing_rename_message_mailingmessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={'permissions': [('set_mailing_status', 'Can set mailing status'), ('can_mailing_disabling', 'Отключение рассылки')], 'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
    ]
